spring:
  application:
    name: github-cicd-demo
  jpa:
    open-in-view: false
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{ip:-}]"
